# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/CLionProjects/cuda

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/CLionProjects/cuda

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/CLionProjects/cuda/CMakeFiles /home/user/CLionProjects/cuda//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/CLionProjects/cuda/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cuda

# Build rule for target.
cuda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda
.PHONY : cuda

# fast build rule for target.
cuda/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda.dir/build.make CMakeFiles/cuda.dir/build
.PHONY : cuda/fast

#=============================================================================
# Target rules for targets named ex1_ex1

# Build rule for target.
ex1_ex1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex1_ex1
.PHONY : ex1_ex1

# fast build rule for target.
ex1_ex1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex1_ex1.dir/build.make CMakeFiles/ex1_ex1.dir/build
.PHONY : ex1_ex1/fast

#=============================================================================
# Target rules for targets named ex2_err1

# Build rule for target.
ex2_err1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex2_err1
.PHONY : ex2_err1

# fast build rule for target.
ex2_err1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex2_err1.dir/build.make CMakeFiles/ex2_err1.dir/build
.PHONY : ex2_err1/fast

#=============================================================================
# Target rules for targets named ex2_err2

# Build rule for target.
ex2_err2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex2_err2
.PHONY : ex2_err2

# fast build rule for target.
ex2_err2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex2_err2.dir/build.make CMakeFiles/ex2_err2.dir/build
.PHONY : ex2_err2/fast

src/Ex1/Ex1.o: src/Ex1/Ex1.cu.o

.PHONY : src/Ex1/Ex1.o

# target to build an object file
src/Ex1/Ex1.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex1_ex1.dir/build.make CMakeFiles/ex1_ex1.dir/src/Ex1/Ex1.cu.o
.PHONY : src/Ex1/Ex1.cu.o

src/Ex1/Ex1.i: src/Ex1/Ex1.cu.i

.PHONY : src/Ex1/Ex1.i

# target to preprocess a source file
src/Ex1/Ex1.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex1_ex1.dir/build.make CMakeFiles/ex1_ex1.dir/src/Ex1/Ex1.cu.i
.PHONY : src/Ex1/Ex1.cu.i

src/Ex1/Ex1.s: src/Ex1/Ex1.cu.s

.PHONY : src/Ex1/Ex1.s

# target to generate assembly for a file
src/Ex1/Ex1.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex1_ex1.dir/build.make CMakeFiles/ex1_ex1.dir/src/Ex1/Ex1.cu.s
.PHONY : src/Ex1/Ex1.cu.s

src/Ex2/err1.o: src/Ex2/err1.cu.o

.PHONY : src/Ex2/err1.o

# target to build an object file
src/Ex2/err1.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex2_err1.dir/build.make CMakeFiles/ex2_err1.dir/src/Ex2/err1.cu.o
.PHONY : src/Ex2/err1.cu.o

src/Ex2/err1.i: src/Ex2/err1.cu.i

.PHONY : src/Ex2/err1.i

# target to preprocess a source file
src/Ex2/err1.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex2_err1.dir/build.make CMakeFiles/ex2_err1.dir/src/Ex2/err1.cu.i
.PHONY : src/Ex2/err1.cu.i

src/Ex2/err1.s: src/Ex2/err1.cu.s

.PHONY : src/Ex2/err1.s

# target to generate assembly for a file
src/Ex2/err1.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex2_err1.dir/build.make CMakeFiles/ex2_err1.dir/src/Ex2/err1.cu.s
.PHONY : src/Ex2/err1.cu.s

src/Ex2/err2.o: src/Ex2/err2.cu.o

.PHONY : src/Ex2/err2.o

# target to build an object file
src/Ex2/err2.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex2_err2.dir/build.make CMakeFiles/ex2_err2.dir/src/Ex2/err2.cu.o
.PHONY : src/Ex2/err2.cu.o

src/Ex2/err2.i: src/Ex2/err2.cu.i

.PHONY : src/Ex2/err2.i

# target to preprocess a source file
src/Ex2/err2.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex2_err2.dir/build.make CMakeFiles/ex2_err2.dir/src/Ex2/err2.cu.i
.PHONY : src/Ex2/err2.cu.i

src/Ex2/err2.s: src/Ex2/err2.cu.s

.PHONY : src/Ex2/err2.s

# target to generate assembly for a file
src/Ex2/err2.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex2_err2.dir/build.make CMakeFiles/ex2_err2.dir/src/Ex2/err2.cu.s
.PHONY : src/Ex2/err2.cu.s

src/main.o: src/main.cu.o

.PHONY : src/main.o

# target to build an object file
src/main.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda.dir/build.make CMakeFiles/cuda.dir/src/main.cu.o
.PHONY : src/main.cu.o

src/main.i: src/main.cu.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda.dir/build.make CMakeFiles/cuda.dir/src/main.cu.i
.PHONY : src/main.cu.i

src/main.s: src/main.cu.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda.dir/build.make CMakeFiles/cuda.dir/src/main.cu.s
.PHONY : src/main.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cuda"
	@echo "... ex1_ex1"
	@echo "... ex2_err1"
	@echo "... ex2_err2"
	@echo "... src/Ex1/Ex1.o"
	@echo "... src/Ex1/Ex1.i"
	@echo "... src/Ex1/Ex1.s"
	@echo "... src/Ex2/err1.o"
	@echo "... src/Ex2/err1.i"
	@echo "... src/Ex2/err1.s"
	@echo "... src/Ex2/err2.o"
	@echo "... src/Ex2/err2.i"
	@echo "... src/Ex2/err2.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

